// Abbreviations after which a full stop does NOT end the sentence, for English
// sources. It is the list Trados Studio applies to English (its
// EN_Abbreviations resource, Studio 2019): the grid only numbers like the
// client's CAT tool if both skip the very same abbreviations. Case matters
// ("No." and "no." are separate entries).
export const ABBREVIATIONS_EN = new Set([
  "A.", "A.M.", "A.R.", "Acc.", "Am.", "Approx.", "Apr.", "Ariz.",
  "Ark.", "Art.", "Art.-No.", "Asst.", "Aug.", "B.", "B.P.", "B.V.",
  "Bk.", "Bldg.", "Blvd.", "Br.", "Brit.", "Bros.", "Bus.", "C.",
  "C.F.R.", "C.I.F.", "Ca.", "Cal.", "Calif.", "Capt.", "Cf.", "Ch.",
  "Chapt.", "Co.", "Col.", "Conn.", "Corp.", "Cpt.", "D.", "D.C.",
  "D.S.", "D.T.", "D.U.", "Dec.", "Dept.", "Dia.", "Div.", "Dr.",
  "E.", "E.e.", "E.g.", "Eng.", "Engl.", "Esq.", "Est.", "Estd.",
  "Etc.", "Excl.", "F.", "Feb.", "Fig.", "Fr.", "G.", "Gal.",
  "Galv.", "Gov.", "H.", "H.J.", "Hon.", "Hrs.", "I.", "I.I.",
  "I.e.", "Ill.", "Imp.", "Inc.", "Incl.", "Ind.", "Instr.", "Int.",
  "Intl.", "J.", "J.C.", "J.D.", "J.P.", "Jan.", "Jr.", "Jul.",
  "Jun.", "K.", "K.A.", "L.", "Lat.", "Lb.", "Lt.", "Ltd.",
  "M.", "M.A.", "M.D.", "M.P.", "M.P.H.", "Maj.", "Mar.", "Mass.",
  "Max.", "Messrs.", "Mich.", "Min.", "Minn.", "Miss.", "Mont.", "Mr.",
  "Mrs.", "Ms.", "Mss.", "Mt.", "Mx.", "N.", "N.B.", "N.O.S.",
  "N.a.", "Nat.", "Neb.", "Nebr.", "Neg.", "Nev.", "No.", "Nos.",
  "Nov.", "Nr.", "O.", "O.J.", "O.S.", "Oct.", "Okla.", "Ore.",
  "Oreg.", "P.", "P.M.", "Pcs.", "Penn.", "Penns.", "Perm.", "Pg.",
  "Pk.", "Plc.", "Pos.", "Pref.", "Pres.", "Pri.", "Prod.", "Prof.",
  "Prol.", "Pt.", "Pte.", "Pty.", "Pvt.", "Q.", "Qr.", "Qt.",
  "Qty.", "Qu.", "R.", "R.W.", "REV.", "Rd.", "Ref.", "Reg.",
  "Ret.", "Rev.", "Revd.", "S.", "S.A.", "S.A.C.C.", "S.I.", "S.N.",
  "S.r.l.", "Sen.", "Senr.", "Sep.", "Sept.", "Sergt.", "Sgt.", "Sq.",
  "Sr.", "St.", "Suppl.", "T.", "T.G.", "Tel.", "Tenn.", "Tex.",
  "Typ.", "U.", "U.K.", "U.S.", "U.S.C.", "V.", "Va.", "Var.",
  "Vis.", "Viz.", "Vol.", "Vols.", "Vs.", "W.", "W.G.", "W.K.",
  "Wash.", "Wis.", "Wt.", "Wy.", "Wyo.", "X.", "Xt.", "Y.",
  "Y.H.", "Yd.", "Yr.", "Yrs.", "Z.", "a.", "a.k.a.", "a.m.",
  "a.p.", "a.y.b.", "abbr.", "acc.", "acct.", "add.", "adm.", "advt.",
  "aftn.", "ala.", "alas.", "amp.", "an.", "ans.", "approx.", "appx.",
  "apr.", "arr.", "asym.", "auth.", "av.", "avdp.", "ave.", "b.",
  "bart.", "bbl.", "bd.", "bds.", "bk.", "bl.", "bldg.", "bls.",
  "bot.", "bros.", "bsh.", "bt.", "bu.", "bus.", "c.", "c.i.f.",
  "ca.", "capt.", "cath.", "cert.", "cf.", "ch.", "chapt.", "cir.",
  "circ.", "ck.", "cks.", "cl.", "cm.", "co.", "col.", "comp.",
  "conc.", "conn.", "cons.", "cont.", "contd.", "corn.", "corp.", "corr.",
  "cp.", "ct.", "cts.", "cu.", "cub.", "cwt.", "d.", "def.",
  "deg.", "del.", "dep.", "dept.", "dft.", "dia.", "diff.", "dir.",
  "disc.", "disct.", "dist.", "div.", "dk.", "do.", "doc.", "dol.",
  "dors.", "doz.", "dpt.", "dr.", "dur.", "dwt.", "dz.", "e.",
  "e.V.", "e.e.", "e.g.", "ed.", "eg.", "enc.", "eng.", "engl.",
  "esq.", "ess.", "est.", "estd.", "etc.", "excl.", "ext.", "f.",
  "fahr.", "fig.", "fla.", "fm.", "fo.", "fol.", "fr.", "ft.",
  "fur.", "g.", "ga.", "gal.", "galv.", "gen.", "ger.", "gi.",
  "gl.", "glos.", "gns.", "gov.", "gr.", "gs.", "guar.", "h.",
  "h.c.", "h.y.", "hf.", "hhd.", "hon.", "hrs.", "i.", "i.e.",
  "ia.", "ib.", "ibid.", "id.", "ida.", "ill.", "imp.", "in.",
  "inc.", "incl.", "incog.", "ind.", "inst.", "instr.", "ir.", "jr.",
  "ken.", "km.", "kv.", "kw.", "ky.", "l.h.", "la.", "lat.",
  "lb.", "ld.", "ll.", "lon.", "lt.", "ltd.", "m.", "m.p.h.",
  "m.y.a.", "max.", "md.", "med.", "mg.", "mi.", "mil.", "min.",
  "mio.", "misc.", "mm.", "mo.", "mult.", "n.", "n.a.", "n.e.c.",
  "n.o.s.", "nat.", "neg.", "nev.", "no.", "nr.", "o.", "ob.",
  "outl.", "oxon.", "oz.", "p.", "p.a.", "p.m.", "pa.", "par.",
  "pc.", "pcl.", "pcs.", "pd.", "pk.", "plc.", "pos.", "posit.",
  "pp.", "pref.", "pres.", "prev.", "prof.", "prol.", "prot.", "prox.",
  "pt.", "pte.", "pvt.", "qr.", "qt.", "qu.", "quot.", "qy.",
  "r.h.", "r.m.s.", "rd.", "ref.", "reg.", "regd.", "rel.", "resp.",
  "ret.", "retd.", "rev.", "s.", "sec.", "senr.", "seq.", "sh.",
  "soc.", "sp.", "spp.", "sq.", "sr.", "ssp.", "st.", "stg.",
  "stk.", "sub.", "subsp.", "suff.", "suppl.", "suppr.", "t.", "tgm.",
  "typ.", "u.s.", "ut.", "v.", "va.", "var.", "vis.", "viz.",
  "vol.", "vols.", "vs.", "vt.", "wt.", "xt.", "yd.", "yr.",
  "yrs.",
]);
