-- Rename OXIGEN_PROCESSING -> FILE_PROCESSING and OXIGEN_ERROR -> FILE_ERROR in ProjectStatus enum

-- Step 1: Expand enum to include both old and new values
ALTER TABLE `Project` MODIFY COLUMN `status` ENUM('UPLOADED','PROCESSING','OXIGEN_PROCESSING','MTQE_PROCESSING','READY','OXIGEN_ERROR','MTQE_ERROR','FILE_PROCESSING','FILE_ERROR') NOT NULL DEFAULT 'UPLOADED';

-- Step 2: Migrate existing rows
UPDATE `Project` SET `status` = 'FILE_PROCESSING' WHERE `status` = 'OXIGEN_PROCESSING';
UPDATE `Project` SET `status` = 'FILE_ERROR' WHERE `status` = 'OXIGEN_ERROR';

-- Step 3: Drop old values by redefining column with final enum
ALTER TABLE `Project` MODIFY COLUMN `status` ENUM('UPLOADED','PROCESSING','FILE_PROCESSING','MTQE_PROCESSING','READY','FILE_ERROR','MTQE_ERROR') NOT NULL DEFAULT 'UPLOADED';
