CREATE TABLE `project_tms` (
    `projectId` VARCHAR(191) NOT NULL,
    `tmId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`projectId`, `tmId`),
    INDEX `project_tms_tmId_idx`(`tmId`),
    CONSTRAINT `project_tms_projectId_fkey`
        FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `project_tms_tmId_fkey`
        FOREIGN KEY (`tmId`) REFERENCES `tms`(`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO `project_tms` (`projectId`, `tmId`)
SELECT p.`id`, t.`id`
FROM `projects` p
JOIN (
    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
    UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
    UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
    UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34
    UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39
    UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44
    UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49
) nums
    ON p.`tmIds` IS NOT NULL
    AND JSON_TYPE(p.`tmIds`) = 'ARRAY'
    AND nums.n < JSON_LENGTH(p.`tmIds`)
JOIN `tms` t
    ON t.`id` = COALESCE(
        JSON_UNQUOTE(JSON_EXTRACT(p.`tmIds`, CONCAT('$[', nums.n, '].id'))),
        JSON_UNQUOTE(JSON_EXTRACT(p.`tmIds`, CONCAT('$[', nums.n, ']')))
    );

ALTER TABLE `projects`
    DROP COLUMN `tmIds`;
